# Generated by Django 4.0.3 on 2022-05-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
